name: Bump Homebrew formula

on:
  workflow_run:
    workflows: ["Push SAF-CLI to NPM and GPR"]
    types:
      - completed
jobs:
  update-formula:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get all tags
        run: git fetch --tags origin
      - name: Extract version
        id: extract-version
        run: echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: saf-cli
          homebrew-tap: mitre/homebrew-saf
          base-branch: main
          download-url: https://registry.npmjs.org/@mitre/saf/-/saf-${{ steps.extract-version.outputs.tag }}.tgz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_PAT }}
