name: Run SAF-CLI E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
       platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
     - uses: actions/checkout@v4

     - name: Setup Node.js ${{ matrix.platform }}
       uses: actions/setup-node@v4
       with:
        node-version: "18"
        check-latest: true
        cache: 'npm'

     - name: Install dependencies ${{ matrix.platform }}
       run: npm ci

     - name: Prepack ${{ matrix.platform }}
       run: npm run prepack

     - name: Run e2e tests ${{ matrix.platform }}
       run: npm run test
